# Generated by Django 3.1.6 on 2022-06-28 12:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('healthapp', '0003_blood_donation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctor',
            name='dob',
        ),
        migrations.RemoveField(
            model_name='doctor',
            name='image',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='dob',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='image',
        ),
        migrations.DeleteModel(
            name='Blood_Donation',
        ),
    ]
